### ISSUE TITLE
Can this be installed with cabal?

### ISSUE THREAD

**Issue by schrum2** [FortOyer/worldturtle-haskell#2]
I tried the command
```
cabal install worldturtle
```
but got the following errors regarding dependency conflicts:
```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: worldturtle-0.2.0.0 (user goal)
[__1] next goal: lens (dependency of worldturtle)
[__1] rejecting: lens-5.0.1 (conflict: worldturtle => lens>=4.18.1 && <4.20)
[__1] skipping: lens-5 (has the same characteristics that caused the previous
version to fail: excluded by constraint '>=4.18.1 && <4.20' from
'worldturtle')
[__1] trying: lens-4.19.2
[__2] next goal: template-haskell (dependency of lens)
[__2] rejecting: template-haskell-2.17.0.0/installed-2.17.0.0 (conflict: lens
=> template-haskell>=2.4 && <2.17)
[__2] skipping: template-haskell-2.17.0.0 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=2.4 && <2.17'
from 'lens')
[__2] rejecting: template-haskell-2.16.0.0, template-haskell-2.15.0.0,
template-haskell-2.14.0.0, template-haskell-2.13.0.0,
template-haskell-2.12.0.0, template-haskell-2.11.1.0,
template-haskell-2.11.0.0, template-haskell-2.10.0.0,
template-haskell-2.9.0.0, template-haskell-2.8.0.0, template-haskell-2.7.0.0,
template-haskell-2.6.0.0, template-haskell-2.5.0.0, template-haskell-2.4.0.1,
template-haskell-2.4.0.0, template-haskell-2.3.0.1, template-haskell-2.3.0.0,
template-haskell-2.2.0.0 (constraint from non-upgradeable package requires
installed instance)
[__2] fail (backjumping, conflict set: lens, template-haskell)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: lens, template-haskell, worldturtle
```

If it matters, I'm on a Windows 10 machine.

**Comment by aneilmac** [comment]
Hi Jacob, 

Sorry for the delay in replying. It was built with stack in mind, and I hadn't looked too deeply into naked cabal builds. (Perhaps this was the wrong choice. I am not too confident in this area.)

I'm sure this can be fixed, though. I'll give it a bash to see if I can massage the dependencies into something congruent.

**Comment by aneilmac** [comment]
@schrum2 On my end, with a fresh install of cabal on a Windows 10 machine, `cabal install worldturtle` is successful.

This is with ghc 8.10.1 and cabal 3.2.0.0.

**Comment by schrum2** [comment]
Just tried this on a different machine with a fresh Haskell install and it failed with the same error message. I'm using ghc 9.0.1

**Comment by tomsmeding** [comment]
@aneilmac What happens with ghc 9 is that worldturtle depends on lens < 4.20, and lens 5 (the first version >= 4.20) is the first version that allows template-haskell 2.17 in its dependency ranges. The template-haskell library is forcibly synchronised with the ghc version, and ghc 9 requires usage of template-haskell >= 2.17. All together this means that the lens < 4.20 constraint that worldturtle has in the cabal file prevents building with ghc 9. (This is all independent of stack/cabal as build tool.)

I've had at least one report that worldturtle builds using lens 5; this can be reproduced by installing ghc 9, making a project that depends on worldturtle, and building that project using `cabal build --allow-newer=lens`.

If you are able to test that worldturtle works properly with lens 5 (and 5.0.1, I suppose -- though assuming lens follows PVP that should be fine), then if you update the upper bound on lens, people using ghc 9 will be able to use worldturtle as well.

Thanks for the hard work and no hurry :)

**Comment by aneilmac** [comment]
@tomsmeding Cheers for the detailed explanation. That really helps demystify the whole thing. I managed to get a 9.0.1 build up and running, and was able to verify that worldturtle compiled after fixing the version bounds. Tests look kosher so I'm going to push this change up and close this issue. 

@schrum2 Sorry for the (long) delay in dealing with this. I hope this fixes your problem. Let me know if there are any further problems.
